use bigdata;

CREATE TABLE ACCOUNT(
  ACCOUNT_NO CHAR(20) PRIMARY KEY,
  BALANCE INT NOT NULL
);

CREATE TABLE CUSTOMER (
CUSTOMER_NO CHAR(5) PRIMARY KEY,
CUSTOMER_NAME VARCHAR(20) NOT NULL,
CUSTOMER_CITY VARCHAR(10)
); 


CREATE TABLE DEPOSITOR(

ACCOUNT_NO CHAR(5) ,
CUSTOMER_NO CHAR(5) ,
PRIMARY KEY (ACCOUNT_NO ,CUSTOMER_NO)
);

ALTER TABLE CUSTOMER ADD DATE_OF_BIRTH DATE;

ALTER TABLE ACCOUNT MODIFY BALANCE DECIMAL(12,2);

ALTER TABLE DEPOSITOR RENAME COLUMN ACCOUNT_NO TO A_NO;

ALTER TABLE DEPOSITOR RENAME COLUMN CUSTOMER_NO TO C_NO;

ALTER TABLE DEPOSITOR RENAME TO DEPOSITOR_INFO;

ALTER TABLE DEPOSITOR_INFO
ADD CONSTRAINT FK_DEPOSITOR_ACCOUNT FOREIGN KEY (A_NO) REFERENCES ACCOUNT(ACCOUNT_NO),
ADD CONSTRAINT FK_DEPOSITOR_CUSTOMER FOREIGN KEY (C_NO) REFERENCES CUSTOMER(CUSTOMER_NO);

INSERT INTO ACCOUNT (ACCOUNT_NO, BALANCE) VALUES
('A001', 5000.00),
('A002', 1500.00),
('A003', 200000.00);

INSERT INTO CUSTOMER (CUSTOMER_NO, CUSTOMER_NAME) VALUES
('C001', 'John Doe', 'KHL'),
('C002', 'Jane Smith', 'DHK'),
('C003', 'Tom Brown', 'NYC');

INSERT INTO CUSTOMER (CUSTOMER_NO, CUSTOMER_NAME, CUSTOMER_CITY,DATE_OF_BIRTH) VALUES

('C004', 'AVOCADO', 'LOS','2020-01-10');

INSERT INTO DEPOSITOR_INFO (A_NO, C_NO) VALUES
('A001', 'C001'),
('A002', 'C002'),
('A003', 'C003');

SELECT ACCOUNT_NO FROM ACCOUNT WHERE BALANCE<100000;

SELECT CUSTOMER_NAME FROM CUSTOMER WHERE CUSTOMER_CITY = 'KHL';

SELECT * FROM ACCOUNT, DEPOSITOR_INFO;

SELECT * FROM CUSTOMER NATURAL JOIN DEPOSITOR_INFO;

SELECT CUSTOMER_NAME, CUSTOMER_CITY FROM CUSTOMER
 WHERE CUSTOMER_NO IN (SELECT C_NO FROM DEPOSITOR_INFO);
 
 
SELECT * FROM CUSTOMER WHERE CUSTOMER_NO IN
(SELECT C_NO FROM DEPOSITOR_INFO WHERE A_NO IN
(SELECT ACCOUNT_NO FROM ACCOUNT WHERE BALANCE > 1000));


SELECT * FROM ACCOUNT WHERE BALANCE BETWEEN 5000 AND 10000
OR ACCOUNT_NO IN (SELECT A_NO FROM DEPOSITOR_INFO WHERE C_NO IN
(SELECT CUSTOMER_NO FROM CUSTOMER WHERE CUSTOMER_CITY = 'DHK'));

UPDATE CUSTOMER SET CUSTOMER_CITY = 'KLN' WHERE CUSTOMER_CITY = 'KHL';
UPDATE CUSTOMER SET CUSTOMER_NO = '301' WHERE CUSTOMER_NO = '101';


DELETE FROM ACCOUNT;
DELETE FROM CUSTOMER;
DELETE FROM DEPOSITOR_INFO;

