use lab10;

select * from pokemon;

DELIMITER //
CREATE FUNCTION gettype(p VARCHAR(100))
RETURNS VARCHAR(100)
DETERMINISTIC
NO SQL
BEGIN
declare t VARCHAR(100);
SELECT TYPE_NAME INTO t FROM TYPES 
WHERE TYPE_ID IN (
    SELECT PRIMARY_TYPE_ID FROM POKEMON WHERE NAME = "Pikachu"
    UNION
    SELECT SECONDARY_TYPE_ID FROM POKEMON WHERE NAME = "Pikachu"
);
RETURN t;
END //
DELIMITER ;

SELECT  gettype("Pikachu");

