use lab5;

CREATE TABLE CUSTOMER (
CUSTOMER_NO CHAR (5) PRIMARY KEY ,
CUSTOMER_NAME VARCHAR (20) NOT NULL ,
CUSTOMER_CITY VARCHAR (10)
) ;
CREATE TABLE ACCOUNT (
ACCOUNT_NO CHAR (5) PRIMARY KEY ,
BALANCE DECIMAL (12 ,2) NOT NULL
) ;
CREATE TABLE DEPOSITOR (
CUSTOMER_NO CHAR (5) ,
ACCOUNT_NO CHAR (5) ,
PRIMARY KEY ( CUSTOMER_NO , ACCOUNT_NO )
) ;


INSERT INTO ACCOUNT (ACCOUNT_NO, BALANCE) 
VALUES ('A-101', 5000.00), 
       ('A-102', 15000.00), 
       ('A-103', 25000.00), 
       ('A-104', 8000.00);


INSERT INTO CUSTOMER (CUSTOMER_NO, CUSTOMER_NAME, CUSTOMER_CITY) 
VALUES ('C-101', 'A-101'), 
       ('C-102', 'A-102');


INSERT INTO DEPOSITOR (CUSTOMER_NO, ACCOUNT_NO) 
VALUES ('C-101', 'A-101'), 
       ('C-102', 'A-102');


INSERT INTO CUSTOMER (CUSTOMER_NO, CUSTOMER_NAME, CUSTOMER_CITY) 
VALUES ('C-103', 'A-103'), 
       ('C-104', 'A-104');


